awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/10X.id_287.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/10X.id_287.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_287.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_562.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_562.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_562.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1280.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1280.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1280.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1351.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1351.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1351.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1423.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1423.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1423.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1613.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1613.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1613.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1639.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_1639.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_1639.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_4932.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_4932.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_4932.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/10X.id_5207.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/10X.id_5207.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/10X.id_5207.allbarcode.txt_list_2
awk '{print $1"/1"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_28901.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_1
awk '{print $1"/2"}' /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/SSRlist/300X.id_28901.allbarcode.txt > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_2
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_1 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_1.fq.gz
/Users/yanweiqi/GitHub/MetaTrass/tools//seqtk subseq FQ2 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_2 |gzip > /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_2.fq.gz
rm -f /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_1 /Users/yanweiqi/GitHub/MetaTrass/Test//dir2_taxonomy/id2fq/300X.id_28901.allbarcode.txt_list_2
