python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/287_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/287 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/287/287_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/287/287_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/287.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/287/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/562_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/562 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/562/562_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/562/562_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/562.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/562/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/1280_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1280 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1280/1280_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1280/1280_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/1280.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1280/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/1351_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1351 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1351/1351_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1351/1351_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/1351.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1351/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/1423_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1423 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1423/1423_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1423/1423_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/1423.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1423/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/1613_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1613 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1613/1613_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1613/1613_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/1613.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1613/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/1639_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1639 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1639/1639_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/1639/1639_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/1639.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/1639/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/4932_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/4932 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/4932/4932_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/4932/4932_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/4932.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/4932/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/5207_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/5207 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/5207/5207_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/5207/5207_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/5207.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/5207/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//quast.py -r ref_fa_DIR/28901_genomic.fa -t 10 --min-identity 90 -o /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/28901 /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/28901/28901_scaffold.fa
python3 /Users/yanweiqi/GitHub/MetaTrass/tools//contig_purify.py -rawContig /Users/yanweiqi/GitHub/MetaTrass/Test//dir3_assembly/supernova/28901/28901_scaffold.fa -purifySeq /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/purify/28901.fa -quastAlnTsv /Users/yanweiqi/GitHub/MetaTrass/Test/dir3_assembly/quast/28901/contigs_reports/all_alignments_scaffold.tsv -IDY 90 -PCT 50
